name: SerialKey
version: 1.0.0
author: Skyost
main: fr.skyost.serialkey.bukkit.SerialKey
api-version: 1.13
commands:
  serialkey:
    description: With /serialkey getkey operators can get a key to the door they are facing
    usage: /serialkey getkey

permissions:
  serialkey.craft.key:
    description: Allows you to craft a key
    default: true
  serialkey.craft.masterkey:
    description: Allows you to craft a master key
    default: op
  serialkey.craft.keyclone:
    description: Allows you to craft a key clone
    default: true
  serialkey.craft.bunchofkeys:
    description: Allows you to craft a bunch of keys
    default: true
  serialkey.craft.padlockfinder:
    description: Allows you to craft a padlock finder
    default: true
  serialkey.use.key:
    description: Allows you to use a key
    default: true
  serialkey.use.masterkey:
    description: Allows you to use a master key
    default: op
  serialkey.use.bunchofkeys:
    description: Allows you to use a bunch of keys
    default: true
  serialkey.use.padlockfinder:
    description: Allows you to use a padlock finder
    default: true
  serialkey.command.getkey:
    description: Allows you to use /serialkey getkey
    default: op
